### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by bernhardreiter** [jsommers/pytricia#10]
Hi,
thanks for making pytricia available as Free Software!

Regarding the license in detail:
 * Wouldn't make sense to have a library like this be available under 
a license with less 'freedom protection'? (The FSF for instance recommends the https://www.gnu.org/licenses/license-list.en.html#apache2 Apache 2.0 license if you want to do this.
Another option would be the GNU Lesser GPL v>=2.1). Usually for a tiny library: less Freedom protection can result in higher usage. This is good for Free Software because for a tiny library people will often not consider changing the license and alternatively instead of using pytricia just pick a different library.
 * Is the current license meant to be GNU GPL v==2 or GNU GPL v>=2? I suggest to add a sentence for this to the README.md. (Usually this is stated with the license file itself and GNU GPL says "or at your option later version" or so. This is good, because otherwise you'll stay incompatible with GNU GPL v>=3 or LGPL v>=3.)

To state my interest: Currently I am helping https://intelmq.org/ and they would rather replace py-radix within pyasn to get the license situation cleared.  

Best Regards

**Comment by jsommers** [comment]
Thanks for your comments and questions.  As far as changing the license, let me think about it --- it's not out of the question, just need to consider for a bit.  As for current license, it is meant to be GPL==2.0.  I'll get back you again soon (I'm traveling, will be back next week).

**Comment by bernhardreiter** [comment]
@jsommers thanks for considering my request and for clarification of the current license. (If you are interested in my background: I am a full time Free Software person https://intevation.de/~bernhard/index.en.html ). My suggestion of changing the license is based on experience (and some research) if you want to get more detailed arguments and just read one article, I recommend: https://www.dwheeler.com/essays/gpl-compatible.html. In section 9 Wheeler suggests: 

>  If you release software under the GPL (solely or as a dual-license), you should include the “version X or later” clause

**Comment by jsommers** [comment]
@bernhardreiter On further consideration, I will likely relicense Pytricia as LGPL >= 2.1.  I'm away/remote until next week so nothing will happen until then.

**Comment by bernhardreiter** [comment]
@jsommers GNU LGPL v>=2.1 would be a big licensing improvement! Looking forward to it. :)

(May I ask why you did decide against Apache 2.0 or the X11 license, which may add a bit of chance of even wider distribution? I think that GNU LGPL is fine, especially as it allows usage in proprietary applications and for a python module it is quite easy anyway to technically allow its exchange with a never version. The drawback is: for small libraries, some users do not like the efforts they have to go through to do a compliant distribution of the source code. Feel completely free to ignore this question.)

**Comment by jsommers** [comment]
Updated here and on pypi.

**Comment by bernhardreiter** [comment]
@jsommers Thanks!

**Comment by mkgvt** [comment]
Having both GPL3 COPYING and LGPL3 COPYING.LESSER is confusing. I suggest only having one COPYING containing the LGPL3 text per the license changes above.
