### ISSUE TITLE
Error when installing on python 2.7 64bit

### ISSUE THREAD

**Issue by kamakay** [jsommers/pytricia#14]
Hi!

I'am using a standard python 2.7 64bit environment, and when executing pip install pytricia I receive this error message.
Any suggestion? Should I use 32bit only distribution of python?

Thanks
Rob

`Collecting pytricia
  Using cached pytricia-0.9.4.tar.gz
Installing collected packages: pytricia
  Running setup.py install for pytricia ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\robert~1
.gra\\appdata\\local\\temp\\pip-build-o0qlxf\\pytricia\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.rea
d().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\robert~1.gra\appdat
a\local\temp\pip-xw9vem-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'pytricia' extension
    creating build
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    C:\............i\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /no
logo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\include -Ic:\python27\PC /Tcpytricia.c /Fobuild\temp.win-amd64-2.7\Release\
pytricia.obj
    pytricia.c
    pytricia.c(19) : fatal error C1083: Cannot open include file: 'arpa/inet.h': No such file or directory
    error: command 'C:\\...........\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\
VC\\Bin\\amd64\\cl.exe' failed with exit status 2
`

**Comment by jsommers** [comment]
Pytricia hasn't been tested at all on any Windows systems, e.g., cygwin, native, or otherwise. The error message above comes about because Pytricia needs a standard C header file on UNIX-like systems which it apparently cannot find.   I can't comment any further than that since I am very much unfamiliar with mingw or doing any of this on windows. Sorry.

I may consider supporting Windows systems in the future, but for now they're not supported at all.

**Comment by jsommers** [comment]
BTW, I just created an enhancement req to (eventually) support Windows since the issue has come up before.

**Comment by kamakay** [comment]
Thanks! If you have an idea on how to solve it I am available to support you.

Rob
